name: 'Pre-build dev container image and push to github container registry' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        name: [jax, pytorch, latex]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: devcontainers/ci@v0.3
        with:
          # Change this to point to your image name
          subFolder: ${{ matrix.name }}
          imageName: ghcr.io/mazhengcn/devcontainers/${{ matrix.name }}}
          cacheFrom: ghcr.io/mazhengcn/devcontainers/${{ matrix.name }}
          push: always
