name: Pre-build dev containers and push 
on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 0'
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        name: [jax, pytorch, latex]
        include:
          - cuda_version: [11, 12]
            name: jax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: devcontainers/ci@v0.3
        with:
          # Change this to point to your image name
          subFolder: ${{ matrix.name }}/${{ matrix.cuda_version }}}
          imageName: ghcr.io/mazhengcn/devcontainers/${{ matrix.name }}
          cacheFrom: ghcr.io/mazhengcn/devcontainers/${{ matrix.name }}
          - if: ${{ matrix.cuda_version }}
            imageTag: ${{ matrix.cuda_version }}
          push: always
